### ISSUE TITLE
Fails to return info on CentOS

### ISSUE THREAD

**Issue by DonJayamanne** [nexssp/os#4]
Thanks for this package.
While using on centos found it fails with the following error
```
[root@fd78521ad880 zeromq.js]# nexssp-os get
@nexssp/os - v2.0.30
/usr/lib/node_modules/@nexssp/os/lib/distro.js:54
          return { key: [s[0]], value: s[1].trim ? s[1].trim() : s[1] }
                                            ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at /usr/lib/node_modules/@nexssp/os/lib/distro.js:54:45
    at Array.map (<anonymous>)
    at Object.module.exports.get (/usr/lib/node_modules/@nexssp/os/lib/distro.js:52:10)
    at module.exports (/usr/lib/node_modules/@nexssp/os/lib/cli/commands/get.js:9:23)
    at Object.runCommand (/usr/lib/node_modules/@nexssp/os/node_modules/@nexssp/plugin/index.js:213:38)
    at Object.<anonymous> (/usr/lib/node_modules/@nexssp/os/bin/nexssp-os.js:9:12)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
```

**Comment by nexssp** [comment]
Thanks for fixing this issue!
